swagger: "2.0"
info:
  title: demo-app
  version: ""
host: 0.0.0.0
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /openapi.json:
    get:
      summary: Download ./gen/http/openapi.json
      operationId: pgload#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /pgload:
    post:
      tags:
      - pgload
      summary: load pgload
      operationId: pgload#load
      parameters:
      - name: LoadRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PgloadLoadRequestBody'
          required:
          - count
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PgloadLoadResponseBody'
      schemes:
      - http
definitions:
  PgloadLoadRequestBody:
    title: PgloadLoadRequestBody
    type: object
    properties:
      count:
        type: integer
        description: How many records to generate in the table
        example: 8603081991435869249
        format: int64
    example:
      count: 326365449501293430
    required:
    - count
  PgloadLoadResponseBody:
    title: 'Mediatype identifier: application/json; view=default'
    type: object
    properties:
      code:
        type: integer
        description: result code
        example: 6385578980826583310
        format: int64
      status:
        type: string
        description: status info
        example: Velit beatae nam autem.
    description: LoadResponseBody result type (default view)
    example:
      code: 5213264074844113834
      status: Voluptate ipsum quia et.
    required:
    - code
    - status
